// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0z2QREHKeMTJASx7sNH0o3XpvcclM9jc',
    appId: '1:497709388361:web:e078d4368acac4a52a6598',
    messagingSenderId: '497709388361',
    projectId: 'fortis-db147',
    authDomain: 'fortis-db147.firebaseapp.com',
    storageBucket: 'fortis-db147.firebasestorage.app',
    measurementId: 'G-JLGY5WB9ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4zh39jPomwqnPuKHPCXnVhNoVuigwRM',
    appId: '1:497709388361:android:efd40eabd8bdc0a52a6598',
    messagingSenderId: '497709388361',
    projectId: 'fortis-db147',
    storageBucket: 'fortis-db147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxWzePSQXwtlZSRB3C2kXanKNozzmaTpU',
    appId: '1:497709388361:ios:12cffb24817fcd342a6598',
    messagingSenderId: '497709388361',
    projectId: 'fortis-db147',
    storageBucket: 'fortis-db147.firebasestorage.app',
    iosBundleId: 'com.example.fortis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxWzePSQXwtlZSRB3C2kXanKNozzmaTpU',
    appId: '1:497709388361:ios:12cffb24817fcd342a6598',
    messagingSenderId: '497709388361',
    projectId: 'fortis-db147',
    storageBucket: 'fortis-db147.firebasestorage.app',
    iosBundleId: 'com.example.fortis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0z2QREHKeMTJASx7sNH0o3XpvcclM9jc',
    appId: '1:497709388361:web:011061fd78db8c612a6598',
    messagingSenderId: '497709388361',
    projectId: 'fortis-db147',
    authDomain: 'fortis-db147.firebaseapp.com',
    storageBucket: 'fortis-db147.firebasestorage.app',
    measurementId: 'G-8MMZMXK4TF',
  );

}